
num = int(input('enter a number entre 0 et 5 :'))

if (num == 0):
    print('')
elif (num == 1):
    print('    *   ')
    print('  *    *')
    print('*        *')
    print('  *    *')
    print('    *   ')
elif (num == 2):
    print('            *     ')
    print('          *   *          ')
    print('       *         *          ')
    print(' ******            ******     ')
    print(' *                      *  ')
    print('  *                    *  ')
    print('    *                 *  ')
    print('   *                  *  ')
    print('  *                    *  ')
    print(' *                      *  ')
    print(' ******            ******     ')
    print('       *         *          ')
    print('          *   *          ')
    print('            *     ')
elif (num >= 3):
    print('                  *               ')
    print('                *   *               ')
    print('              *      *               ')
    print('            *         *               ')
    print('***********             ***********      ')
    print(' *                              *')
    print('  *                           *')
    print('   *                        *')
    print('    *                     *')
    print('    *                     *')
    print('   *                       *')
    print('  *                         *')
    print(' *                           *')
    print('*                             *')
    print('********             ***********      ')
    print('         *         *               ')
    print('           *      *               ')
    print('            *   *               ')
    print('              *               ')
